export const categories = [
  "All",
  "Gaming",
  "Programming",
  "Music",
  "React Routers",
  "Live",
  "Gadgets",
  "Computers",
  "John Snow",
  "Podcasts",
  "Others",
];

export const shortVideos = [
  {
    id: 2,
    title: "Mobile app development",
    viewCount: "132k",
    image: require("../assets/images/short5.png"),
  },
  {
    id: 3,
    title: "Tesla's Wireless Charger: Explained!",
    viewCount: "2M",
    image: require("../assets/images/short3.png"),
  },
  {
    id: 1,
    title: "Reasons you should learn React Native",
    viewCount: "355k",
    image: require("../assets/images/short2.png"),
  },
  {
    id: 4,
    title: "Rare Moments in Football 🥶🤩",
    viewCount: "167k",
    image: require("../assets/images/short4.png"),
  },
  {
    id: 5,
    title: "Fastest Way to Learn React in 2023 🔥",
    viewCount: "1.2M",
    image: require("../assets/images/short1.png"),
  },
];

export const videos = [
  {
    id: 10,
    title: "I bought every MacBook Ever.",
    channelTitle: "Mrwhosetheboss",
    thumbnail: require("../assets/images/thumb10.png"),
    avatar: require("../assets/images/avatar10.jpg"),
    viewCount: "2.4M",
    duration: "27:01",
    publishedText: "1 day ago",
  },
  {
    id: 1,
    title: "Homeless Man Buys A Lamborghini",
    channelTitle: "MrBeast",
    thumbnail: require("../assets/images/thumb1.png"),
    avatar: require("../assets/images/avatar1.png"),
    viewCount: "130M",
    duration: "14:50",
    publishedText: "2 years ago",
  },
  {
    id: 8,
    title: "Cash Has CUSTOM HEARTS in Minecraft!",
    channelTitle: "Cash",
    thumbnail: require("../assets/images/thumb8.png"),
    avatar: require("../assets/images/avatar8.jpg"),
    viewCount: "640K",
    duration: "21:35",
    publishedText: "16 hours ago",
  },
  {
    id: 7,
    title: "Mutated Imposter in Among Us",
    channelTitle: "SSundee",
    thumbnail: require("../assets/images/thumb7.png"),
    avatar: require("../assets/images/avatar7.jpg"),
    viewCount: "980K",
    duration: "17:07",
    publishedText: "15 hours ago",
  },

  {
    id: 4,
    title: "Top 10 CSS One Liners That Will Blow Your Mind",
    channelTitle: "developedbyed",
    thumbnail: require("../assets/images/thumb4.png"),
    avatar: require("../assets/images/avatar4.png"),
    viewCount: "400K",
    duration: "7:45",
    publishedText: "1 Month ago",
  },
  {
    id: 9,
    title:
      "Brawl Stars: Brawl Talk - BLING! 2 Brawlers, a new Showdown, and MORE!",
    channelTitle: "Brawl Stars",
    thumbnail: require("../assets/images/thumb9.png"),
    avatar: require("../assets/images/avatar9.jpg"),
    viewCount: "3.7M",
    duration: "11:03",
    publishedText: "1 day ago",
  },
  {
    id: 5,
    title: "Jimmy Neutron Isn't Smart.",
    channelTitle: "Microwave Society",
    thumbnail: require("../assets/images/thumb5.png"),
    avatar: require("../assets/images/avatar5.jpg"),
    viewCount: "220K",
    duration: "15:17",
    publishedText: "5 days ago",
  },
  {
    id: 2,
    title: "I Spent 30 Days Freelancing on Upwork",
    channelTitle: "Kenny Gunderman",
    thumbnail: require("../assets/images/thumb2.png"),
    avatar: require("../assets/images/avatar2.png"),
    viewCount: "1M",
    duration: "4:30",
    publishedText: "5 months ago",
  },
  {
    id: 6,
    title: "YoungBoy Never Broke Again - Big Truck [Official Music Video]",
    channelTitle: "YoungBoy Never Broke Again",
    thumbnail: require("../assets/images/thumb6.png"),
    avatar: require("../assets/images/avatar6.jpg"),
    viewCount: "1.9M",
    duration: "2:48",
    publishedText: "2 days ago",
  },
  {
    id: 3,
    title: "6 Of My Personal Tips When Learning To Code",
    channelTitle: "Traversy Media",
    thumbnail: require("../assets/images/thumb3.png"),
    avatar: require("../assets/images/avatar3.png"),
    viewCount: "151K",
    duration: "6:00",
    publishedText: "1 year ago",
  },
];
